### PR TITLE
osx : fix the inverted version test

### PR DESCRIPTION
**Pull request by pmalhaire**
switched flags for this https://github.com/hishamhm/htop/pull/728

### CODE REVIEW

**Comment by Explorer09** [comment]
Hello. I wonder what's the reason for inverting the function behavior of CompareKernelVersion() ?
Also, when we are improving the function, is it okay to add `static` qualifier to CompareKernelVersion? If you are familar with C you know what it means.

**Comment by pmalhaire** [comment]
@Explorer09 I do invert the function because I made a mistake while writing it. See https://github.com/hishamhm/htop/pull/728
It makes sense tout make it static.

**Comment by pmalhaire** [comment]
@hishamhm I accidentaly inverted the test when I compactes the code. This is a fix for this

**Comment by ylluminarious** [comment]
@pmalhaire @Explorer09 After testing this patch on my own and verifying the test with some logging, I can confirm that this patch fixes the problem and it should no longer occur. Unless, of course, something other than `DarwinProcess_scanThreads` is causing the problem, but there is no evidence to indicate that.

**Comment by ylluminarious** [comment]
I applied this patch and left the resultant program running for **4 hours** on 10.13.3 and didn't crash... I suggest that this patch be merged as soon as possible.

**Comment by hishamhm** [comment]
Merged! Thanks, @pmalhaire! A new release is coming this weekend!

**Comment by ylluminarious** [comment]
@hishamhm Thanks again! Sorry for the false relief in the previous PR... but thanks for your patience!

**Pull request merged**
