### PR TITLE
Fix FreeBSD CPU bars calculation

### LINKED ISSUE #456: CPU usage is wrong on FreeBSD
All of htop's bars are set to 100% nice

```
  1  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   4  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   7  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   10 [||||||||||||||||||||||||||||||||||||||||||||100.0%]
  2  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   5  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   8  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   11 [||||||||||||||||||||||||||||||||||||||||||||100.0%]
  3  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   6  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   9  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   12 [||||||||||||||||||||||||||||||||||||||||||||100.0%]
  Avg[||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||100.0%]   Tasks: 781; 15 running
  Mem[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                        11.7G/63.4G]   Load average: 3.23 2.89 2.70
```

while top accurately reports:

```
CPU:  2.4% user, 17.3% nice,  2.7% system,  0.2% interrupt, 77.4% idle
```

The load is caused mainly by a nice process that uses about 200% CPU. This individual process CPU usage however is incorrectly reported in htop as ~1%.

(htop 2.0.1 from FreeBSD ports)

### PR DESCRIPTION
**Pull request by Cubox-**
This reverts commit f554f08fa92f8440faa853b5fa4d588829959c8a.

Fixes #456

### CODE REVIEW

**Comment by Cubox-** [comment]
This commit fixes the CPU bars, but breaks multi-thread process CPU usage. Working on a fix.

**Comment by hishamhm** [comment]
So, is this good to merge as is?

**Comment by Cubox-** [comment]
I would recommand someone else testing it, but it is good to merge.

**Comment by main--** [comment]
I already reported that this works just fine on my machine (10.3-RELEASE), but @gaod disagrees in https://github.com/hishamhm/htop/issues/456#issuecomment-207589589.

**Comment by hishamhm** [comment]
@main-- @gaod @Cubox- now I wonder if this is sensitive to FreeBSD version?...

**Comment by Cubox-** [comment]
I tested using 10.3-RELEASE

**Comment by MartinBoeh** [comment]
Tested using 10.2 works fine please include this asap.

:+1:

**Comment by main--** [comment]
While it doesn't fix the issue for @gaod at least, it doesn't seem to regress anything either, so it seems like merging this should be safe either way: It keeps being broken for some users, but it's fixed for others.

**Comment by gaod** [comment]
I think merging this commit is a good way. I'll keep looking why it doesn't work on my environment.

**Comment by hishamhm** [comment]
Merged! Thank you all for the information, and @gaod, let me know if you find something!

**Pull request merged**
