### PR TITLE
Issue #502 update Session ID column

### PR DESCRIPTION
**Pull request by kamyarrasta**

### CODE REVIEW

**Comment by hishamhm** [comment]
Hi! Thanks for contributing!

Did you test this PR? It seems to change the width of the header.

**Comment by kamyarrasta** [comment]
Hi!
I have tested it on linux but I have not noticed that the header is changed. Just updated it and hopefully it works correctly this time. BTW, thanks for lovely htop!

**Comment by hishamhm** [comment]
Thank you for revising it! Merging!

**Comment by kamyarrasta** [comment]
Sure! Thanks

**Pull request merged**
