### PR TITLE
Add the "Active users" meter.

### PR DESCRIPTION
**Pull request by nojhan**
A text meter that display a list of users owning processes that are actually running.
The list is truncated to the size of the display.

Tested on linux (Ubuntu 14.04).

### CODE REVIEW

**Comment by nojhan** [comment]
PR #222 extends this patch with more features.
I let this one opened in case you prefer this simpler implementation.

**Comment by hishamhm** [comment]
This patch has problems. Checking with strstr() doesn't work... This implementation (and PR #222) will miss user 'anna' if user 'adrianna' is already in the list. Also, you're assuming the process list is sorted so that running processes are at the top.

**Comment by nojhan** [comment]
I will fix the implementation for the name search.

Concerning the assumption, aren't the following lines supposed to guarantee that the process list is sorted?
```
pl->settings->sortKey = PERCENT_CPU;
pl->settings->direction = 1;
ProcessList_sort(pl);
```

**Comment by hishamhm** [comment]
Meters shouldn't alter the process list in any way (including re-sorting it).

**Comment by nojhan** [comment]
Willco.

**Pull request closed without merging**
