### PR TITLE
use unicode block elements for graphical meter

### PR DESCRIPTION
**Pull request by eworm-de**
Not sure whether or not this should be merged... The issue with using braille characters is:

* looks ugly if true type font is used, depending on the font it can be even completly useless (with Fira Mono for example)
* breaks completly if no braille characters are available

I wondered whether it makes sense to use [unicode block elements](https://en.wikipedia.org/wiki/Block_Elements) instead:

* no unusable truetype stuff

But the drawback is:

* The resolution is limited

So this is RFC... Waiting for comments. :D

### CODE REVIEW

**Comment by LukasLedvina** [comment]
Hi, I'm not testing that, but Meter.c:368 "const double dot = (1.0 / 16);" should be 1.0/8  --- vertical resolution of the graph (and also few other lines, see below). In your solution the bar is increasing from 0% to 12.5%, than is constant up to 25%, increasing to 37.5%, constant to 50%,...

 Meter.c:368 16->8
 Meter.c:375 12->6
 Meter.c:385 4->2

How about introducing variable "pixPerRow" (pixels per console row).
Lukas

**Comment by eworm-de** [comment]
> Hi, I'm not testing that, but Meter.c:368 "const double dot = (1.0 / 16);" should be 1.0/8 --- vertical resolution of the graph (and also few other lines, see below). In your solution the bar is increasing from 0% to 12.5%, than is constant up to 25%, increasing to 37.5%, constant to 50%,...

Ah, of course you are right. This was intended to be a quick'n'dirty base for discussion only, but better do it right. ;)

> How about introducing variable "pixPerRow" (pixels per console row).

Did that in #221.

**Comment by hishamhm** [comment]
@eworm-de the issue with TrueType fonts depends a lot on which fonts you happen to have available, so it's just as true with Braille as it is with block characters. Both sets may or may not be missing.

If you use a font which lacks the necessary characters, it's possible to write a fontconfig configuration file to override that segment of Unicode with characters from another font.

**Comment by eworm-de** [comment]
> the issue with TrueType fonts depends a lot on which fonts you happen to have available, so it's just as true with Braille as it is with block characters. Both sets may or may not be missing.

I've tried Fira Mono in my terminal. That font does have braille characters, but it has dots when set and circles when unset. It's nearly impossible to see a difference on small font size and/or low resolution display. That is why I thought I should try something else that can break less.

However I still prefer braille characters.

> If you use a font which lacks the necessary characters, it's possible to write a fontconfig configuration file to override that segment of Unicode with characters from another font.

Ah, nice! Did not know that. Thanks for the hint!

**Pull request closed without merging**
