### PR TITLE
fix calloc() calls

### LINKED ISSUE #261: calloc() problem
It seems like [here](https://github.com/hishamhm/htop/blob/master/Header.c#L92):

```
char* name = calloc(64, sizeof(char*));
```

The `size_t` value should be `sizeof(char)`, not `sizeof(char*)`

Found with the Clang static analyzer.

### PR DESCRIPTION
**Pull request by eworm-de**
* size_t nmemb (number of elements) first, then size_t size
* do not assume char is size 1 but use sizeof()
* allocate for char, not pointer to char (found by Michael McConville,
  fixes #261)

### CODE REVIEW

**Comment by jes** [comment]
Just a note to say that sizeof(char) is defined to be 1.

**Comment by eworm-de** [comment]
This is true for linux, but I think there are other architectures that handle this different, no?
Or was it the other way round that sizeof(char) is always 1 but that is not always one byte?

However... Using sizeof() is the save option and it does not bring any extra cost as the compiler optimizes this.

**Comment by hishamhm** [comment]
> This is true for linux, but I think there are other architectures that handle this different, no?

Not in the last 40 years, I think :) Certainly not in any platforms that htop runs or is expected to run in the future ;)

**Comment by mmcco** [comment]
> > This is true for linux, but I think there are other architectures that handle this different, no?

> Not in the last 40 years, I think :) Certainly not in any platforms that htop runs or is expected to run in the future ;)

Regardless, it's *definitely* still preferable to use `sizeof(char)` rather than hardcoding an assumed value. It's more readable, it helps static analysis, and it aids portability when someone wants to do something wacky for fun.

**Comment by hugomg** [comment]
FYI, jes is right. The C standard specifies that sizeof(char) should be 1, even if you are on a wachy machine with 9bit chars or something like that

http://stackoverflow.com/questions/2215445/are-there-machines-where-sizeofchar-1

**Comment by mmcco** [comment]
Yeah, y'all are right. I read the above too quickly and saw it only as a "malloc v. calloc" discussion".

**Pull request merged**
