### PR TITLE
Add "p" to Help

### PR DESCRIPTION
**Pull request by mhinz**

### CODE REVIEW

**Comment by Explorer09** [comment]
Such a commit brings me (personally) one question: Do we need to document every Display Options hotkey out there in the F1 help screen? That screen was supposed to be one page and viewable in a standard 80*24 terminal. There was no need to document trivial keys there.

If it's for me, I would rather mention that in the Display Options screen: changing
"Show program path"
to
"Show program path (main screen hotkey: p)"

**Comment by hishamhm** [comment]
@mhinz Thanks for the contribution! But why did you close this PR? I was just going to ask you to keep the "press any key" line where it was.

**Comment by mhinz** [comment]
@hishamhm I just thought there was no interest in this simple patch and I like to keep my open PR list to a minimum. ;-)

**Comment by hishamhm** [comment]
@mhinz sorry for taking so long to review it! It's now merged :)

**Comment by mhinz** [comment]
No worries, it's open source after all. Thanks for this project!

**Pull request merged**
