### PR TITLE
tell GCC 7.x this is explicit fallthough

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by hishamhm** [comment]
doesn't this break when compiled with clang (or other compilers)?

**Comment by eworm-de** [comment]
At least `clang` does not break, but it reports its own warning now. *sigh*
```
ColumnsPanel.c:69:10: warning: declaration does not declare anything [-Wmissing-declarations]
         __attribute__((fallthrough));
```
Tested with `clang` version 4.0.1.

**Comment by Explorer09** [comment]
Wait. Can't GCC detect the fallthrough keyword in comments?
Can we fix the comments as documented in `-Wimplicit-fallthrough` in [GCC Warning Options](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) page?

**Comment by eworm-de** [comment]
I can't make any of these to work here, even when giving extra `-Wimplicit-fallthrough=1`. This is with gcc 7.1.1 on Arch Linux.

**Comment by Explorer09** [comment]
Move the /* else fallthrough */ comment to outside the braces. Will that work?

**Comment by eworm-de** [comment]
Ah, that's the issue! Looks like.

Let me do some more testing before I update the pull request.

**Comment by eworm-de** [comment]
Updated...
Any comment on indention?

**Comment by hishamhm** [comment]
@eworm-de Thank you!

**Pull request merged**
