### PR TITLE
Units and cleanup

### PR DESCRIPTION
**Pull request by eworm-de**
* show units with "i" to indicate binary base
* use define for const values

### CODE REVIEW

**Comment by Earnestly** [comment]
Hm, why lowercase `k` in `kiB`?
Nice changes otherwise.

**Comment by eworm-de** [comment]
Good question... You are right, for IEC units the `K` in `KiB` is written as a capital letter...

**Comment by Earnestly** [comment]
If you don't mind, I'd be grateful if you could change `k` to `K`.  I could
then make use of this PR for my own custom set of patches against htop
(appending .patch to the PR url) as the developer seems to have no interest
doing this.

**Comment by eworm-de** [comment]
Reworked the code and sent pull request #208.

@Earnestly, happy with that?

**Comment by Earnestly** [comment]
@eworm-de No, not really as it uses incorrect prefixes now.  Thanks anyway.

**Pull request closed without merging**
