### PR TITLE
Dynamic unit

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by eworm-de** [comment]
To give an idea of what it looks like:
pr-208

**Comment by hishamhm** [comment]
This is interesting! The more I look at it, the more I get used to it and like it.
Minor nit, though: Meter_human_unit -> Meter_humanUnit

**Comment by eworm-de** [comment]
Ah, sure. Updated to match function naming convention.

**Comment by hishamhm** [comment]
Merged, thanks!!

**Pull request merged**
