### PR TITLE
(Regression) Typo in the word "prority" -> "priority"

### PR DESCRIPTION
**Pull request by koresar**

### CODE REVIEW

**Comment by Explorer09** [comment]
Mark this thing as a merge regression. (Sane as #343)

**Comment by koresar** [comment]
Not sure if you were talking to me. :) Where should I mark it?

**Comment by Explorer09** [comment]
@koresar Ahh, sorry. What I mean was to say the word "(Regression)" on the issue title.
If only @hishamhm has noticed this earlier.

**Comment by koresar** [comment]
I'm not really into your project government rules mate. :) I just came across the bug and decided to help.
Sorry for not reading your contribution guide. No time for that really.

Title changed! :+1: 

cheers

**Comment by Explorer09** [comment]
@koresar  No, it's not "government rules". Just an easy way to bring notice of other developers. :)
In many projects this (Regression) title is common.
By the way, I do not own this project, just a volunteer contributor. :)

**Comment by hishamhm** [comment]
Thank you, @koresar!

(And sorry about the slip-up with the regression thing)

**Pull request merged**
