### PR TITLE
Improve htop.desktop file

### PR DESCRIPTION
**Pull request by rindeal**
- sort entries according to the spec
- add to the `Monitor` category

### CODE REVIEW

**Comment by hishamhm** [comment]
Hi! Thanks for sending a patch.

Im puzzled, though. I always thought order of entries was not relevant in this file format.

**Comment by rindeal** [comment]
For machines it really doesn't matter, but for us, package maintainers who review these files a lot, it's helpful.

**Comment by hishamhm** [comment]
your patch removes `GenericName[zh_CN]`. Why is that?

**Comment by rindeal** [comment]
It does not. If it seems so in GitHub GUI it's because of your changes to the `desktop-menu-entry` branch. My patch was created before `zh_CN` lines were even added. Here is how the actual patch looks in git:

```diff
commit cba751b0e90c7bbb638c2430efe2a2fe4d9b43c7
Author: Jan Chren (rindeal) <dev.rindeal@gmail.com>
Date:   Fri Mar 24 15:30:16 2017 +0100

    Improve htop.desktop file
    
    - sort entries according to the spec
    - add to the `Monitor` category

diff --git a/htop.desktop b/htop.desktop
index b88d530..53c24cc 100644
--- a/htop.desktop
+++ b/htop.desktop
@@ -1,7 +1,34 @@
 [Desktop Entry]
+Type=Application
 Version=1.0
 Name=Htop
-Type=Application
+GenericName=Process Viewer
+GenericName[ca]=Visor de processos
+GenericName[de]=Prozessanzeige
+GenericName[en_GB]=Process Viewer
+GenericName[es]=Visor de procesos
+GenericName[fi]=Prosessikatselin
+GenericName[fr]=Visualiseur de processus
+GenericName[gl]=Visor de procesos
+GenericName[it]=Visore dei processi
+GenericName[ko]=프로세스 뷰어
+GenericName[nb]=Prosessviser
+GenericName[nl]=Viewer van processen
+GenericName[nn]=Prosessvisar
+GenericName[pl]=Przeglądarka procesów
+GenericName[pt]=Visualizador de Processos
+GenericName[pt_BR]=Visualizador de processos
+GenericName[ru]=Монитор процессов
+GenericName[sk]=Prehliadač procesov
+GenericName[sl]=Pregledovalnik opravil
+GenericName[sr@ijekavian]=Приказивач процеса
+GenericName[sr@ijekavianlatin]=Prikazivač procesa
+GenericName[sr@latin]=Prikazivač procesa
+GenericName[sr]=Приказивач процеса
+GenericName[sv]=Processvisning
+GenericName[tr]=Süreç Görüntüleyici
+GenericName[uk]=Перегляд процесів
+GenericName[zh_TW]=行程檢視器
 Comment=Show System Processes
 Comment[ca]=Mostra els processos del sistema
 Comment[de]=Systemprozesse anzeigen
@@ -21,43 +48,16 @@ Comment[pt_BR]=Mostra os processos do sistema
 Comment[ru]=Просмотр списка процессов в системе
 Comment[sk]=Zobraziť systémové procesy
 Comment[sl]=Prikaz sistemskih opravil
-Comment[sr]=Приказ системских процеса
 Comment[sr@ijekavian]=Приказ системских процеса
 Comment[sr@ijekavianlatin]=Prikaz sistemskih procesa
 Comment[sr@latin]=Prikaz sistemskih procesa
+Comment[sr]=Приказ системских процеса
 Comment[sv]=Visa systemprocesser
 Comment[tr]=Sistem Süreçlerini Göster
 Comment[uk]=Перегляд системних процесів
 Comment[zh_TW]=顯示系統行程
-Terminal=true
-Exec=htop
 Icon=htop
-Categories=ConsoleOnly;System;
-GenericName=Process Viewer
-GenericName[ca]=Visor de processos
-GenericName[de]=Prozessanzeige
-GenericName[en_GB]=Process Viewer
-GenericName[es]=Visor de procesos
-GenericName[fi]=Prosessikatselin
-GenericName[fr]=Visualiseur de processus
-GenericName[gl]=Visor de procesos
-GenericName[it]=Visore dei processi
-GenericName[ko]=프로세스 뷰어
-GenericName[nb]=Prosessviser
-GenericName[nl]=Viewer van processen
-GenericName[nn]=Prosessvisar
-GenericName[pl]=Przeglądarka procesów
-GenericName[pt]=Visualizador de Processos
-GenericName[pt_BR]=Visualizador de processos
-GenericName[ru]=Монитор процессов
-GenericName[sk]=Prehliadač procesov
-GenericName[sl]=Pregledovalnik opravil
-GenericName[sr]=Приказивач процеса
-GenericName[sr@ijekavian]=Приказивач процеса
-GenericName[sr@ijekavianlatin]=Prikazivač procesa
-GenericName[sr@latin]=Prikazivač procesa
-GenericName[sv]=Processvisning
-GenericName[tr]=Süreç Görüntüleyici
-GenericName[uk]=Перегляд процесів
-GenericName[zh_TW]=行程檢視器
+Exec=htop
+Terminal=true
+Categories=System;Monitor;ConsoleOnly;
 Keywords=system;process;task
```

**Comment by rindeal** [comment]
fixed the merge conflicts

**Comment by hishamhm** [comment]
Thank you for updating! Merged

**Pull request merged**
