### PR TITLE
Fixup for a rebuild issue in rev `47cf1532b0c9fb`.

### PR DESCRIPTION
**Pull request by uprego**

### CODE REVIEW

**Comment by uprego** [comment]
https://github.com/hishamhm/htop/commit/47cf1532b0c9fb

**Comment by uprego** [comment]
Oops, duplicate of https://github.com/hishamhm/htop/pull/789

**Comment by uprego** [comment]
I was caught in the underlying issue while trying to fix the Travis CI builds of https://github.com/hishamhm/htop/pull/792.

**Comment by hishamhm** [comment]
#789 was merged, thank you!

**Pull request closed without merging**
