### PR TITLE
Run modern gcc

### PR DESCRIPTION
**Pull request by szepeviktor**
gcc-6

### CODE REVIEW

**Comment by szepeviktor** [comment]
There is one warning only: https://travis-ci.org/hishamhm/htop/jobs/310520033#L837

**Comment by hishamhm** [comment]
Hi! Thanks for looking into this! However, the description mentions gcc, but that build ended up running clang. So maybe there's a problem in this patch?

**Comment by szepeviktor** [comment]
@hishamhm The bottom one is the new gcc build: https://travis-ci.org/hishamhm/htop/builds/310521395

**Comment by hishamhm** [comment]
@szepeviktor from the looks of the Travis logs, it seems this is still running gcc 4: https://travis-ci.org/hishamhm/htop/jobs/310521400

**Comment by szepeviktor** [comment]
@hishamhm It may be because of a temporary network failure: https://travis-ci.org/hishamhm/htop/jobs/310521400#L422
Package manager was not able to install gcc 6.
Could you restart the build?

**Pull request closed without merging**
